In [43]:
import numpy as np


In [100]:
def row_binary(v):
    for i in range(len(v)):
        if v[i]%2 == 0:
            v[i] = 0
        else:
            v[i] = 1 
    return v

def row_trans(v):
    for i in range(len(v)):
        if v[i] == 0:
            v[i] = 0
        else:
            v[i] = 1 

            return v
def column(matrix, i):
    return [row[i] for row in matrix]

def basis(n):
    nums = np.array([a for a in range(2**(n))]) 
    bin_nums = (((nums.reshape(-1,1) & (2**np.arange(n)))) != 0).astype(int)
    a = bin_nums[:,::-1]
    return a

def G_b(G,b):
    Gb = []
    for i in range(len(b)):
        if b[i] == 1:
            Gb.append(column(G,i))
    Gb = np.array(Gb)
    return Gb.T

def matrix_trans(A):
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if A[i][j] == 0:
                A[i][j] = 0
            else:
                A[i][j] = 1
    return A

def matrix_binary(A):
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if A[i][j]%2 == 0:
                A[i][j] = 0
            else:
                A[i][j] = 1
    return A
def num_1_pos(d):
    get_indexes = lambda x, xs: [i for (y, i) in zip(xs, range(len(xs))) if x == y]
    num_1 = get_indexes(1,d)
    return num_1,len(num_1)

def num_0_pos(d):
    get_indexes = lambda x, xs: [i for (y, i) in zip(xs, range(len(xs))) if x == y]
    num_0 = get_indexes(0,d)
    return num_0,len(num_0)

def commYZ(d):
    num_1 = num_1_pos(d)
    num_0 = num_0_pos(d)
    B = basis(num_1[1])
    C = []
    for i in range(B.shape[0]):
        b = list(B[i])
        for j in range(len(num_0[0])):             
            b.insert(num_0[0][j],0)
        C.append(b)
    return np.array(C)
def G_comm(G):
    G_comm = []
    for i in range(G.shape[1]):
        g = column(G, i)
        G_comm.append(commYZ(g))
    return G_comm

def commbya(a,G):
    w = num_1_pos(list(a))
    z = np.zeros((G.T).shape[1])
    for j in range(w[1]):
        z += G.T[w[0][j]]
        z = row_binary(z)
    return z 


G = np.array([[1,0,0,0,1,1,0],
              [0,1,0,0,1,0,1],
              [0,0,1,0,0,1,1],
              [0,0,0,1,1,1,1]])


## Depend on G create b

In [101]:
G_com = G_comm(G)
# depend on G create b
print(G_com)

[array([[0, 0, 0, 0],
       [1, 0, 0, 0]]), array([[0, 0, 0, 0],
       [0, 1, 0, 0]]), array([[0, 0, 0, 0],
       [0, 0, 1, 0]]), array([[0, 0, 0, 0],
       [0, 0, 0, 1]]), array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1]]), array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1]]), array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1]])]


## bG Operation

In [110]:
BG = []
b = []
for j in range(len(G_com)):
    l = np.array(G_com[j]).shape[0]
    for i in range(l):
        f = G_com[j][i].dot(G)
        b.append(G_com[j][i]) # b depends on G_column
        BG.append(f)             
BG = np.array(BG)
BG = matrix_binary(BG)
b = np.array(b)      
             

In [111]:
for i  in range(BG.shape[0]):
    Gb = G_b(G,BG[i]) #Generate G_b from bG  
    if Gb.size > 0:
        print('--- b depend on G -----')
        print('b = ',b[i])
        print('bG = ',BG[i]) #bG
        print('-- Generator matrix ---')
        print(G)
        print('-- G_b matrix ---')
        print(Gb)    #G_b
        a = basis(Gb.shape[1]) #Generate a from G_b
        print('--- a depend on G_b -----')
        print(a)
        print('###################')
        for j in range((a.shape[0]-1)):
                print('When a is:  ',a[j+1])
                z = commbya(a[j+1],Gb)
                print('The commute result is:  ',z)
        print('---- aG_b operation -----')
        aGb = a.dot(Gb.T)  # aG_b operation
        aGb = matrix_binary(aGb)
        print(aGb)

        print('$$$$$$$$$$$$$')
        
        
    else:
        continue;
    
    


--- b depend on G -----
b =  [1 0 0 0]
bG =  [1 0 0 0 1 1 0]
-- Generator matrix ---
[[1 0 0 0 1 1 0]
 [0 1 0 0 1 0 1]
 [0 0 1 0 0 1 1]
 [0 0 0 1 1 1 1]]
-- G_b matrix ---
[[1 1 1]
 [0 1 0]
 [0 0 1]
 [0 1 1]]
--- a depend on G_b -----
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
###################
When a is:   [0 0 1]
The commute result is:   [1. 0. 1. 1.]
When a is:   [0 1 0]
The commute result is:   [1. 1. 0. 1.]
When a is:   [0 1 1]
The commute result is:   [0. 1. 1. 0.]
When a is:   [1 0 0]
The commute result is:   [1. 0. 0. 0.]
When a is:   [1 0 1]
The commute result is:   [0. 0. 1. 1.]
When a is:   [1 1 0]
The commute result is:   [0. 1. 0. 1.]
When a is:   [1 1 1]
The commute result is:   [1. 1. 1. 0.]
---- aG_b operation -----
[[0 0 0 0]
 [1 0 1 1]
 [1 1 0 1]
 [0 1 1 0]
 [1 0 0 0]
 [0 0 1 1]
 [0 1 0 1]
 [1 1 1 0]]
$$$$$$$$$$$$$
--- b depend on G -----
b =  [0 1 0 0]
bG =  [0 1 0 0 1 0 1]
-- Generator matrix ---
[[1 0 0 0 1 1 0]
 [0 1 0 0 1 0 1]
 [0 

In [108]:
a = np.array([0,0,1,0])
F = np.array([[1,0,0,1],
               [0,1,0,1],
               [0,0,0,0],
               [0,0,1,1]])


def commbya(a,G):
    w = num_1_pos(list(a))
    z = np.zeros((G.T).shape[1])
    for j in range(w[1]):
        z += G.T[w[0][j]]
        z = row_binary(z)
    return z 
print(F)
z = commbya(a,F)
print(z)

[[1 0 0 1]
 [0 1 0 1]
 [0 0 0 0]
 [0 0 1 1]]
[0. 0. 0. 1.]


In [ ]:
for j in range(a.shape[0]):
    if  (a[j] == np.zeros(a.shape[1])).all():
        continue;
    else:
        print('When a is:  ',a[j])
        z = commbya(a,Gb)
        print('The commute result is:  ',z)